services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: tradingdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tradingdb"]
      interval: 10s
      retries: 5
      start_period: 10s